Fail for polybar and powermenu

diff --git a/modules/polybar b/modules/polybar
--- a/modules/polybar
+++ b/modules/polybar
@@ -2,7 +2,11 @@
 
 source "${HOME}/.cache/wal/colors.sh"
 
-# TODO: Fail if polybar is not installed
+if ! command -v "polybar" 2>&1 >/dev/null
+then
+    echo "polybar could not be found"
+    exit 1
+fi
 
 printf "color0 = $color0
 color1 = $color1
diff --git a/modules/powermenu b/modules/powermenu
--- a/modules/powermenu
+++ b/modules/powermenu
@@ -2,7 +2,10 @@
 
 source "${HOME}/.cache/wal/colors.sh"
 
-# TODO: Fail if Rofi Powermenu is not installed
+if [ ! -d "${HOME}/.config/rofi/powermenu" ]; then
+    echo "Could not find Rofi Powermenu. Install it from: https://github.com/adi1090x/rofi"
+    exit 1
+fi
 
 printf "* {
     background:                     $color0;
